name: Main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

    #  - name: Gradle wrapper validation
    #    uses: gradle/wrapper-validation-action@v1
        
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
                    
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
         
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        

#      - name: Write key
#        run: |
#          echo buildWithGitSuffix=true >> local.properties
#          echo storePassword=password >> local.properties
#          echo keyAlias=alias >> local.properties
#          echo keyPassword=password >> local.properties
#          echo fileDir=`pwd`/key.jks >> local.properties
#          keytool -genkey -dname "cn=A, ou=D, o=G, l=P, st=M, c=I" -keystore key.jks -storepass password -alias alias -keyalg RSA -keysize 4096 -validity 10000
          
#      - name: Cache gradle
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
#          restore-keys: ${{ runner.os }}-gradle-

#      - name: Gradle prebuild
#        run: |
#          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
#          ./gradlew prebuild
          
#      # Run Tests Build
#      - name: Run gradle tests
#        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug 
        run: ./gradlew assembleDebug
       # echo "releaseName=$(ls app/build/outputs/apk/debug/app-debug.apk | awk -F '(/|.apk)' '{print $5}')" >> $GITHUB_OUTPUT

      # Create APK Release
      - name: Build apk release
        run: ./gradlew assemble
       # echo "releaseName=$(ls app/build/outputs/apk/release/app-release.apk | awk -F '(/|.apk)' '{print $5}')" >> $GITHUB_OUTPUT
        
      # Upload Artifact Build
      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: /app/build/outputs/apk/
          include-hidden-files: true

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: /app/build/outputs/apk/
          include-hidden-files: true
          

